---
# tasks file for httpd
 

- name: "Installing httpd"
  package:
          name: "{{ software_name }}"
          state: present


- name: "Deploying webpages"
  copy: 
          dest: "/var/www/html"
          src: "/root/roles/httpd/files/ip.php"
  notify: "restarted services"

- name: "Starting Services"
  service:
          name: "{{ software_name }}"
          state: started
